#ifndef __SGP_MODELFILESETTINGFLAG_HEADER__
#define __SGP_MODELFILESETTINGFLAG_HEADER__

enum SGP_MF1MESH_RENDERFLAG
{
	SGPMESHRF_NONE = 0,

	SGPMESHRF_TWOSIDED = 1,
	SGPMESHRF_ALPHABLEND = 1 << 1,
	SGPMESHRF_ALPHATEST = 1 << 2,
};

enum SGP_MF1MESH_CHUNKFLAG
{
	SGPMESHCF_NORMAL = 0,

	SGPMESHCF_AVMESH,
	SGPMESHCF_DECAL,
	SGPMESHCF_BUMP,


	SGPMESHCF_BBRD,						// Look towards the camera plane (fast)
	SGPMESHCF_BBRD_CAMERAPOINT,			// Look towards the camera point (better effect but more expensive)
	SGPMESHCF_BBRD_VERTICALGROUND,		// Y Axial locked Billboard
	//SGPMESHCF_BBRD_APERTURE,
};


#endif		// __SGP_MODELFILESETTINGFLAG_HEADER__